apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reactapp
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reactapp
  targetCPUUtilizationPercentage: 10