apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: awsproject-gateway
spec:
  selector:
    istio: ingressgateway service of LoadBalancer, which creates AWS ELB
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"