apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: guestbook-virtualservice
  namespace: awsproject
spec:
  hosts:
  - "*"
  gateways:
  - awsproject-gateway
  http:
  - match:
    - uri:
        regex: '^/api/employee'
      ignoreUriCase: true
    route:
    - destination:
        host: javaapp
        port:
          number: 8080
  - route:
    - destination:
        host: reactapp
        port:
          number: 80