apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-database-data-volume
  name: mysql-database-data-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi