apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database-data-volume
spec:
  storageClassName: cloud-ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2